### ISSUE TITLE
Qeusiton on Medication - Condtion data

### ISSUE THREAD

**Issue by babysarojini** [IHTSDO/snomed-fhir-cds-service#13]
Medication - Condition XLSX has only a few rows of data. How can we obtain a comprehensive set of conditions and drugs for contraindications?

**Comment by kaicode** [comment]
The intention of this project is to provide the technical capability for Medication-Condition clinical decision support.
The few rows included in the project demonstrate this capability.

A larger set of rules could be developed by clinicians as part of an implementation project. I believe there are comercial sets of rules available but I have no experience of these.

It may be worth reaching out to your national SNOMED CT release centre to see if there are regional sets of rules available or enough interested parties to start a collaborative development of them. If rules exist using other code systems we have open access tooling to assist in mapping to SNOMED CT. 

SNOMED CT is perfectly suited to CDS because of its meaning based poly-hierarchies, generated from its description logic authoring process.

**Comment by babysarojini** [comment]
understood..thank you.
